server:
  port: 521

# 定义 Feign 的延迟时间 单位：秒
time: 1

spring:
  application:
#   自己在 Eureka 中的服务名称
    name: cloud-payment-service
#   设置 Zipkin 监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
#     采样率值介于 0 到 1 之间, 1则表示全部采样
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: mq0000

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    druid filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      validation-query: select 1
      test-while-idle: true
eureka:
  client:
#   表示自己要注册EurekaServer
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: patment521
    prefer-ip-address: true
#   Eureka 客户端向服务端发送心跳的时间间隔 单位秒
    lease-renewal-interval-in-seconds: 1
#   Eureka 客户端在收到最后一次心跳后等待时间上限 超时将剔除 单位秒
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nay.springcloud.entities
