server:
  port: 401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #配置 Nacos 地址
#        server-addr: 10.43.1.52:1111    #配置 Nacos 集群地址(即Nginx暴露出来的端口)
    sentinel:
      transport:
        dashboard: localhost:8080       #配置 Sentinel Dashboard 地址
        port: 8719                      #默认8719 假如被占用 会依次+扫描 知道找到未被占用的端口
#       以下为持久化配置
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        exclude: '*'

# 激活Sentinel 对 openfeign 的支持
feign:
  sentinel:
    enabled: true