server:
  port: 520

spring:
  application:
    name: cloud-consumerconsul-order
  cloud:
    consul:
      host: 10.43.1.52
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#       解决红×
        prefer-ip-address: true