server:
  port: 520

spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    #   表示自己要注册EurekaServer
    register-with-eureka: true
#   从 Eureka 抓取已有的信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: consumer520
    prefer-ip-address: true
    #   Eureka 客户端向服务端发送心跳的时间间隔 单位秒
    lease-renewal-interval-in-seconds: 1
    #   Eureka 客户端在收到最后一次心跳后等待时间上限 超时将剔除 单位秒
    lease-expiration-duration-in-seconds: 2
ribbon:
# 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 2000
# 指建立链接所用的时间 适用于网络状况正常情况下 两端所用时间
  ConnectTimeout: 2000

# debug 级别监控这个接口
logging:
  level:
    com.nay.springcloud.service.PaymentFeignService: debug