server:
  port: 520

spring:
  application:
    name: cloud-consumer-order
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #     采样率值介于 0 到 1 之间, 1则表示全部采样
        probability: 1
eureka:
  client:
    #   表示自己要注册EurekaServer
    register-with-eureka: true
#   从 Eureka 抓取已有的信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: consumer520
    prefer-ip-address: true
    #   Eureka 客户端向服务端发送心跳的时间间隔 单位秒
    lease-renewal-interval-in-seconds: 1
    #   Eureka 客户端在收到最后一次心跳后等待时间上限 超时将剔除 单位秒
    lease-expiration-duration-in-seconds: 2